### ISSUE TITLE
Doesn't connect - like it froze 

### ISSUE THREAD

**Issue by TheMitten1702** [Sun-Research-University/SwitchPresence-Rewritten#44]
Please don't judge me :c 

When I want to connect, the client says "Attempting to connect to server". There may be something I need to do on my Switch but what? Instructions are unclear. help.

**Comment by SunTheCourier** [comment]
Sounds like you didnt get the right IP look in the wifi settings and make sure you're connected to the same network with the correct IP to the switch.
