### ISSUE TITLE
Unchecking "Show Time Lapsed" still shows elapsed time

### ISSUE THREAD

**Issue by nfitzen** [Sun-Research-University/SwitchPresence-Rewritten#47]
This is in the GUI application; I haven't tried the CLI yet.

I've tried:
- Disconnecting, unchecking, reconnecting
- Restarting the client after unchecking

**Comment by SquadCraftFTW** [comment]
Same issue here

**Comment by SunTheCourier** [comment]
Actually fixed internally ^^
