### ISSUE TITLE
[10.0.4 Atmosphere] Switch Presence Rewritten Manager Crashes upon Boot

### ISSUE THREAD

**Issue by fortem0** [Sun-Research-University/SwitchPresence-Rewritten#48]
Have tried using both hekate and fusee primary payloads, to no avail. Is there a reason behind this?

**Comment by SunTheCourier** [comment]
Please provide system info and a crash log

**Comment by fortem0** [comment]
Don't know what more system info I can provide but here:

Switch was bought on launch
Using Atmosphere
No AutoRCM
10.0.4

Crash log is attached
[crash.log](https://github.com/Sun-Research-University/SwitchPresence-Rewritten/files/4907501/crash.log)

**Comment by SunTheCourier** [comment]
you're atmosphere is extremely out of date please update it

**Comment by fortem0** [comment]
That's odd, I only installed homebrew on my Switch less than a week ago. I did do it before once 2 years ago, but that was with a completely different SD card and PC. I'll try updating it and report back

**Comment by fortem0** [comment]
Nope. Updated Atmosphere, but it still crashes immediately.

**Comment by SunTheCourier** [comment]
can i get a new crash report

**Comment by fortem0** [comment]
[crash2.log](https://github.com/Sun-Research-University/SwitchPresence-Rewritten/files/4908448/crash2.log)

**Comment by SunTheCourier** [comment]
you're latest crash is due to to sharenx not sure if sharing this crash log was intentional?

**Comment by fortem0** [comment]
I fixed it. Apparently turning off ShareNX made it finally work. Don't know why that was the case
